In [1]:
#cleaning the csv file

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [3]:
car_data = Path("../car details v4.csv")

In [4]:
car_df = pd.read_csv(car_data)
car_df.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [5]:
car_df.count()

Make                  2059
Model                 2059
Price                 2059
Year                  2059
Kilometer             2059
Fuel Type             2059
Transmission          2059
Location              2059
Color                 2059
Owner                 2059
Seller Type           2059
Engine                1979
Max Power             1979
Max Torque            1979
Drivetrain            1923
Length                1995
Width                 1995
Height                1995
Seating Capacity      1995
Fuel Tank Capacity    1946
dtype: int64

In [14]:
car_df = car_df.dropna(how='any')
car_df.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [15]:
car_df.count()

Make                  1874
Model                 1874
Price                 1874
Year                  1874
Kilometer             1874
Fuel Type             1874
Transmission          1874
Location              1874
Color                 1874
Owner                 1874
Seller Type           1874
Engine                1874
Max Power             1874
Max Torque            1874
Drivetrain            1874
Length                1874
Width                 1874
Height                1874
Seating Capacity      1874
Fuel Tank Capacity    1874
dtype: int64

In [16]:
car_df['Location'].unique()

array(['Pune', 'Ludhiana', 'Lucknow', 'Mangalore', 'Mumbai', 'Coimbatore',
       'Bangalore', 'Delhi', 'Raipur', 'Kanpur', 'Patna', 'Vadodara',
       'Hyderabad', 'Yamunanagar', 'Gurgaon', 'Jaipur', 'Deoghar', 'Agra',
       'Goa', 'Warangal', 'Jalandhar', 'Noida', 'Ahmedabad', 'Mohali',
       'Ghaziabad', 'Kolkata', 'Zirakpur', 'Nagpur', 'Thane', 'Faridabad',
       'Ranchi', 'Chandigarh', 'Amritsar', 'Chennai', 'Navi Mumbai',
       'Udupi', 'Jamshedpur', 'Aurangabad', 'Rudrapur', 'Nashik',
       'Varanasi', 'Salem', 'Dehradun', 'Valsad', 'Haldwani', 'Dharwad',
       'Surat', 'Indore', 'Karnal', 'Panchkula', 'Mysore', 'Rohtak',
       'Ambala Cantt', 'Samastipur', 'Panvel', 'Purnea', 'Bhubaneswar',
       'Kheda', 'Kollam', 'Meerut', 'Ernakulam', 'Kharar', 'Mirzapur',
       'Bhopal', 'Gorakhpur', 'Guwahati', 'Allahabad', 'Muzaffurpur',
       'Faizabad', 'Kota', 'Pimpri-Chinchwad', 'Dak. Kannada',
       'Ranga Reddy', 'Bulandshahar', 'Roorkee'], dtype=object)

In [18]:
#new DF with only Mumbai data
clean_car = car_df.loc[car_df['Location'] == 'Mumbai']
clean_car.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
8,Skoda,Octavia 1.8 TSI Style Plus AT [2017],1390000,2017,56000,Petrol,Automatic,Mumbai,White,First,Individual,1798 cc,177 bhp @ 5100 rpm,250 Nm @ 1250 rpm,FWD,4670.0,1814.0,1476.0,5.0,50.0
9,Nissan,Terrano XL (D),575000,2015,85000,Diesel,Manual,Mumbai,White,First,Individual,1461 cc,84 bhp @ 3750 rpm,200 Nm @ 1900 rpm,FWD,4331.0,1822.0,1671.0,5.0,50.0
10,Hyundai,Elite i20 Sportz 1.2,591000,2017,20281,Petrol,Manual,Mumbai,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,115 Nm @ 4000 rpm,FWD,3985.0,1734.0,1505.0,5.0,45.0
20,Maruti Suzuki,S-Presso VXi AMT,470000,2020,2169,Petrol,Automatic,Mumbai,Grey,First,Individual,998 cc,67 bhp @ 5500 rpm,90 Nm @ 3500 rpm,FWD,3565.0,1520.0,1564.0,5.0,27.0